# Run this workflow every time a new commit pushed to your repository
stages:
  - format       # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  DEPS_DIR: $CI_PROJECT_DIR/deps
  HUNTER_ROOT: $CI_PROJECT_DIR/hunter


clang-format-job:
  stage: format
  variables:
    GIT_CHECKOUT: "true"
  tags:
    - linux
  script:
    - echo "Checking if the code is well formated"
    - clang-format --version
    - $CI_PROJECT_DIR/scripts/ci/run-clang-format.py -r --clang-format-executable clang-format --color always $CI_PROJECT_DIR/developers/

# compilation on macos
compile-developers-job-mac:
  stage: build
  variables:
    COMPILER: "clang++"
    BUILD_TYPE: "Release"
    CXXFLAGS: "-Werror=#warnings"
    GIT_CHECKOUT: "true"
  tags:
    - mac
  script:
    - mkdir -p $CI_PROJECT_DIR/build_mac #-p builds if not there and does nothing otherwise

    - cd $CI_PROJECT_DIR/build_mac
    - export CXX=$COMPILER
    - echo $CXX
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS_DEBUG="-g0" -DHUNTER_CONFIGURATION_TYPES=$BUILD_TYPE -Wdev

    - echo "Building developer folder"
    - cd developers
    - make -j 4

  cache:
    key : developers-mac
    paths :
      - $CI_PROJECT_DIR/build_mac/developers/


compile-developers-job-linux:
  stage: build
  variables:
    COMPILER: "g++"
    BUILD_TYPE: "Release"
    CXXFLAGS: "-Werror=cpp"
    GIT_CHECKOUT: "true"

  tags:
    - linux
  script:
    - mkdir -p $CI_PROJECT_DIR/build_linux #-p builds if not there and does nothing otherwise

    - cd $CI_PROJECT_DIR/build_linux
    - export CXX=$COMPILER
    - echo $CXX

    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS_DEBUG="-g0" -DHUNTER_CONFIGURATION_TYPES=$BUILD_TYPE -Wdev
    - echo "Building developer folder"
    - cd developers
    - make -j 4
  cache:
    key : developers-linux
    paths :
      - $CI_PROJECT_DIR/build_linux/developers/

test-developer-job-mac:
  stage: test
  tags:
    - mac
  script:
    - echo "Testing developer folder master solutions"
    - cd $CI_PROJECT_DIR/build_mac
    - chmod +x $CI_PROJECT_DIR/scripts/ci/test_developers.sh
    - $CI_PROJECT_DIR/scripts/ci/test_developers.sh
  cache:
    key : developers-mac
    paths :
      - $CI_PROJECT_DIR/build_mac/developers/

test-developer-job-linux:
  stage: test
  tags:
    - linux
  script:
    - echo "Testing developer folder master solutions"
    - cd $CI_PROJECT_DIR/build_linux
    - chmod +x $CI_PROJECT_DIR/scripts/ci/test_developers.sh
    - $CI_PROJECT_DIR/scripts/ci/test_developers.sh
  cache:
    key : developers-linux
    paths :
      - $CI_PROJECT_DIR/build_linux/developers/

